import { CheckCircle2, XCircle, AlertTriangle, HelpCircle, Clock, FileText, BarChart3, Shield, Sparkles } from "lucide-react";
import type { DetectionResult } from "@/types/detection";
import { VERDICT_CONFIG } from "@/constants";
import { cn } from "@/lib/utils";
import { useState } from "react";
import ScoreRing from "./ScoreRing";
import FeatureBar from "./FeatureBar";
import SentenceHighlight from "./SentenceHighlight";

interface ResultPanelProps {
  result: DetectionResult;
}

const VERDICT_ICONS = {
  ai: XCircle,
  mixed: AlertTriangle,
  uncertain: HelpCircle,
  human: CheckCircle2,
};

export default function ResultPanel({ result }: ResultPanelProps) {
  const config = VERDICT_CONFIG[result.verdict];
  const Icon = VERDICT_ICONS[result.verdict];
  const [showSentences, setShowSentences] = useState(false);

  const formatDate = (d: Date) => new Date(d).toLocaleString("en-US", {
    month: "short", day: "numeric", hour: "2-digit", minute: "2-digit",
  });

  return (
    <div className="space-y-6 animate-fade-in">
      {/* ── "Made with AI" Banner ─────────────────────────────── */}
      {result.verdict === "ai" && (
        <div className="relative overflow-hidden rounded-2xl border border-red-500/40 bg-gradient-to-r from-red-500/15 via-red-600/10 to-orange-500/10 p-5">
          {/* Animated glow line */}
          <div className="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-transparent via-red-400 to-transparent" />
          <div className="flex items-center gap-3">
            <div className="flex-shrink-0 w-10 h-10 rounded-xl bg-red-500/20 border border-red-500/40 flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-red-400" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-lg font-bold text-red-400 tracking-tight">Made with AI</span>
                <span className="px-2 py-0.5 rounded-full bg-red-500/20 border border-red-500/30 text-xs font-mono text-red-300">
                  {result.aiProbability}% confidence
                </span>
              </div>
              <p className="text-xs text-red-300/70 mt-0.5">
                This content was most likely generated by an AI model (GPT, Claude, Gemini, or similar).
              </p>
            </div>
          </div>
        </div>
      )}

      {/* ── Header verdict ─────────────────────────────────────── */}
      <div className={cn("rounded-2xl border p-6", config.bgColor, config.borderColor)}>
        <div className="flex flex-col sm:flex-row items-center gap-6">
          <div className="flex-shrink-0">
            <ScoreRing aiProbability={result.aiProbability} verdict={result.verdict} />
          </div>
          <div className="flex-1 text-center sm:text-left space-y-3">
            <div className="flex items-center justify-center sm:justify-start gap-2">
              <Icon className={cn("w-5 h-5", config.color)} />
              <h3 className={cn("text-xl font-bold", config.color)}>{config.label}</h3>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">{result.summary}</p>
            <div className="flex flex-wrap gap-4 text-xs font-mono">
              <div className="flex items-center gap-1.5 text-muted-foreground">
                <Shield className="w-3.5 h-3.5" />
                <span>Confidence: <span className="text-foreground font-semibold">{result.confidence}%</span></span>
              </div>
              <div className="flex items-center gap-1.5 text-muted-foreground">
                <BarChart3 className="w-3.5 h-3.5" />
                <span>Human: <span className="text-emerald-400 font-semibold">{result.humanProbability}%</span></span>
              </div>
              {result.wordCount && (
                <div className="flex items-center gap-1.5 text-muted-foreground">
                  <FileText className="w-3.5 h-3.5" />
                  <span>{result.wordCount.toLocaleString()} words</span>
                </div>
              )}
              {result.fileName && (
                <div className="flex items-center gap-1.5 text-muted-foreground">
                  <FileText className="w-3.5 h-3.5" />
                  <span className="truncate max-w-[150px]">{result.fileName}</span>
                </div>
              )}
              <div className="flex items-center gap-1.5 text-muted-foreground">
                <Clock className="w-3.5 h-3.5" />
                <span>{formatDate(result.analyzedAt)}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* ── Feature breakdown ──────────────────────────────────── */}
      <div className="glass rounded-2xl p-6 space-y-5">
        <div className="flex items-center gap-2 mb-2">
          <BarChart3 className="w-4 h-4 text-primary" />
          <h4 className="text-sm font-semibold text-foreground">Detection Feature Breakdown</h4>
        </div>
        <div className="space-y-6">
          {result.features.map((feature, i) => (
            <FeatureBar key={feature.name} feature={feature} delay={i * 100 + 200} />
          ))}
        </div>
      </div>

      {/* ── Sentence-level highlighting (text only) ───────────── */}
      {result.sentences && result.sentences.length > 0 && (
        <div className="glass rounded-2xl p-6 space-y-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <FileText className="w-4 h-4 text-primary" />
              <h4 className="text-sm font-semibold text-foreground">Sentence-Level Analysis</h4>
              <span className="px-2 py-0.5 rounded-full bg-primary/10 border border-primary/20 text-xs font-mono text-primary">
                {result.sentences.length} sentences
              </span>
            </div>
            <button
              onClick={() => setShowSentences(!showSentences)}
              className="text-xs text-primary hover:underline font-mono"
            >
              {showSentences ? "Hide" : "Show"} highlights
            </button>
          </div>
          {showSentences && <SentenceHighlight sentences={result.sentences} />}
          {!showSentences && (
            <p className="text-xs text-muted-foreground">
              Click "Show highlights" to see color-coded sentence-by-sentence AI probability analysis.
            </p>
          )}
        </div>
      )}

      {/* ── Disclaimer ─────────────────────────────────────────── */}
      <div className="rounded-xl bg-muted/30 border border-border p-4 text-xs text-muted-foreground leading-relaxed">
        <strong className="text-foreground">Important:</strong> AI detection is probabilistic, not deterministic. Results should be used as guidance, not proof. False positives and negatives are possible. Always apply human judgment.
      </div>
    </div>
  );
}
